name: Auto Label PRs

on:
  pull_request:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # needed to add labels
    steps:
      - name: Add automerge label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-label "automerge" \
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
