name: Kong Konnect Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  debug-event:
    runs-on: ubuntu-latest
    steps:
      - name: Show event name
        run:
          echo "Event: ${{ github.event_name }}"

      - name: Show if merged flag is present
        run: echo "Merged? ${{ github.event.pull_request.merged }}"

      - name: Dump full event payload
        run: echo '${{ toJson(github.event) }}'

  deploy-kong-config:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: source
      - uses: kong/setup-deck@v1
      - run: deck gateway ping --konnect-control-plane-name hackathon --konnect-token=${{ secrets.KONNECT_TOKEN }} --konnect-addr=https://eu.api.konghq.com
      - run: deck gateway sync source/*.yaml --konnect-token=${{ secrets.KONNECT_TOKEN }} --konnect-addr=https://eu.api.konghq.com